/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/banana.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useExplode } from '../hooks/useExplode';

export function BananaModel(props) {
  const { nodes, materials } = useGLTF('/models/banana.glb')

  const group = React.useRef();

  useExplode(group, { distance: 50 });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell.geometry}
        material={materials.blinn2SG}
        position={[7.739, -41.725, 7.244]}
      />
      <group position={[1.136, 47.704, 36.744]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell001.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell001_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell009.geometry}
        material={materials.blinn2SG}
        position={[-5.236, 41.791, 29.8]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell011.geometry}
        material={materials.blinn2SG}
        position={[2.72, -14.432, 10.357]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell014.geometry}
        material={materials.blinn2SG}
        position={[-15.099, 1.087, -0.868]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell016.geometry}
        material={materials.blinn2SG}
        position={[24.333, -25.317, -6.957]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell017.geometry}
        material={materials.blinn2SG}
        position={[-10.58, -19.203, 1.476]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell019.geometry}
        material={materials.blinn2SG}
        position={[-7.55, -33.854, 9.145]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell026.geometry}
        material={materials.blinn2SG}
        position={[2.055, 50.655, 9.964]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell027.geometry}
        material={materials.blinn2SG}
        position={[-7.624, 32.396, -3.292]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell031.geometry}
        material={materials.blinn2SG}
        position={[3.888, 33.891, 11.247]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell032.geometry}
        material={materials.blinn2SG}
        position={[11.221, 46.783, 21.578]}
      />
      <group position={[-2.561, -44.213, 17.316]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell025.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell025_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell.geometry}
        material={materials.blinn2SG}
        position={[-5.79, 27.662, 6.377]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell001.geometry}
        material={materials.blinn2SG}
        position={[7.573, 29.412, 16.526]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell002.geometry}
        material={materials.blinn2SG}
        position={[-0.542, 41.502, 16.734]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell003.geometry}
        material={materials.blinn2SG}
        position={[0.065, 39.925, 16.734]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell004.geometry}
        material={materials.blinn2SG}
        position={[5.431, 42.248, 18.561]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell005.geometry}
        material={materials.blinn2SG}
        position={[-6.551, 40.255, 24.277]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell007.geometry}
        material={materials.blinn2SG}
        position={[-1.203, 35.74, 24.285]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell.geometry}
        material={materials.blinn2SG}
        position={[5.335, -33.093, 19.996]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell001.geometry}
        material={materials.blinn2SG}
        position={[5.536, -34.946, 16.359]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell002.geometry}
        material={materials.blinn2SG}
        position={[5.136, -36.984, 16.314]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell004.geometry}
        material={materials.blinn2SG}
        position={[4.414, -31.082, 17.504]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell005.geometry}
        material={materials.blinn2SG}
        position={[6.833, -32.919, 15.323]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell006.geometry}
        material={materials.blinn2SG}
        position={[5.906, -36.072, 16.498]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell007.geometry}
        material={materials.blinn2SG}
        position={[4.878, -30.632, 17.042]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell001.geometry}
        material={materials.blinn2SG}
        position={[-8.959, -0.291, 9.982]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell003.geometry}
        material={materials.blinn2SG}
        position={[7.766, 4.941, 12.639]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell004.geometry}
        material={materials.blinn2SG}
        position={[-11.012, 3.257, 7.941]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell005.geometry}
        material={materials.blinn2SG}
        position={[2.725, 6.465, 11.78]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell006.geometry}
        material={materials.blinn2SG}
        position={[-7.86, 6.404, 8.055]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell.geometry}
        material={materials.blinn2SG}
        position={[1.95, 44.988, 23.11]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell003.geometry}
        material={materials.blinn2SG}
        position={[7.235, 43.72, 14.712]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell006.geometry}
        material={materials.blinn2SG}
        position={[-2.763, 45.715, 22.961]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell007.geometry}
        material={materials.blinn2SG}
        position={[4.39, 43.997, 12.009]}
      />
      <group position={[-0.08, 51.662, 29.574]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell008.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell008_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group position={[2.211, 55.706, 32.808]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell009.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell009_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group position={[-3.565, 49.628, 30.795]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell001_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell001_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell005_cell004.geometry}
        material={materials.blinn2SG}
        position={[-3.762, 50.506, 27.866]}
      />
      <group position={[-0.228, 52.439, 31.233]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell004_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell004_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group position={[-4.253, 55.212, 33.422]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell005_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell005_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group position={[3.936, 51.852, 33.478]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell006_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell005_cell006_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell004_cell.geometry}
        material={materials.blinn2SG}
        position={[3.762, 41.668, 24.646]}
      />
      <group position={[4.206, 55.766, 31.801]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell009.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell009_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group position={[-0.571, 49.202, 28.197]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell001_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell001_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell004_cell003.geometry}
        material={materials.blinn2SG}
        position={[4.302, 44.129, 22.572]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell004_cell004.geometry}
        material={materials.blinn2SG}
        position={[1.776, 44.75, 25.349]}
      />
      <group position={[-0.621, 50.162, 31.329]}>
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell004_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          geometry={nodes.pasted__pCube11_group_cell004_cell004_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell004_cell006.geometry}
        material={materials.blinn2SG}
        position={[0.217, 48.681, 26.038]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell004_cell007.geometry}
        material={materials.blinn2SG}
        position={[0.764, 46.116, 24.555]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell005_cell003_cell.geometry}
        material={materials.blinn2SG}
        position={[0.827, 50.28, 30.721]}
      />
      <group position={[1.526, 52.507, 32.634]}>
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell009.geometry
          }
          material={materials.blinn10SG}
        />
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell009_1.geometry
          }
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell005_cell003_cell002.geometry}
        material={materials.blinn2SG}
        position={[1.117, 50.363, 30.406]}
      />
      <group position={[1.754, 53.802, 31.793]}>
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell002_1.geometry
          }
          material={materials.blinn10SG}
        />
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell002_2.geometry
          }
          material={materials.blinn2SG}
        />
      </group>
      <group position={[1.861, 51.431, 31.836]}>
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell003_1.geometry
          }
          material={materials.blinn10SG}
        />
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell003_2.geometry
          }
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell005_cell003_cell005.geometry}
        material={materials.blinn2SG}
        position={[1.018, 51.098, 31.335]}
      />
      <group position={[1.835, 52.251, 32.106]}>
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell005_1.geometry
          }
          material={materials.blinn10SG}
        />
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell005_2.geometry
          }
          material={materials.blinn2SG}
        />
      </group>
      <group position={[1.866, 53.027, 30.682]}>
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell006_1.geometry
          }
          material={materials.blinn10SG}
        />
        <mesh
          geometry={
            nodes.pasted__pCube11_group_cell005_cell003_cell006_2.geometry
          }
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell.geometry}
        material={materials.blinn2SG}
        position={[5.488, 46.724, 13.622]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell001.geometry}
        material={materials.blinn2SG}
        position={[1.795, 48.89, 19.847]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell002.geometry}
        material={materials.blinn2SG}
        position={[2.613, 43.698, 16.612]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell003.geometry}
        material={materials.blinn2SG}
        position={[5.2, 45.972, 18.676]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell004.geometry}
        material={materials.blinn2SG}
        position={[1.1, 45.154, 17.596]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell005.geometry}
        material={materials.blinn2SG}
        position={[4.033, 48.305, 18.474]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell005_cell006.geometry}
        material={materials.blinn2SG}
        position={[4.712, 45.953, 17.918]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell001.geometry}
        material={materials.blinn2SG}
        position={[5.286, 45.707, 18.646]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell002.geometry}
        material={materials.blinn2SG}
        position={[2.678, 43.872, 16.691]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell003.geometry}
        material={materials.blinn2SG}
        position={[2.347, 45.004, 17.736]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell004.geometry}
        material={materials.blinn2SG}
        position={[0.362, 40.782, 20.891]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell005.geometry}
        material={materials.blinn2SG}
        position={[2.737, 41.064, 18.946]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell006.geometry}
        material={materials.blinn2SG}
        position={[2.358, 43.917, 16.639]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell004_cell007.geometry}
        material={materials.blinn2SG}
        position={[2.563, 42.632, 19.372]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell.geometry}
        material={materials.blinn2SG}
        position={[-3.281, 41.923, 18.307]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell001.geometry}
        material={materials.blinn2SG}
        position={[1.165, 41.994, 18.846]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell002.geometry}
        material={materials.blinn2SG}
        position={[-0.475, 41.735, 18.898]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell003.geometry}
        material={materials.blinn2SG}
        position={[-5.613, 42.897, 17.715]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell004.geometry}
        material={materials.blinn2SG}
        position={[0.939, 44.325, 15.436]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell005.geometry}
        material={materials.blinn2SG}
        position={[1.246, 46.792, 19.684]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell006.geometry}
        material={materials.blinn2SG}
        position={[-4.974, 44.758, 21.389]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell002_cell007.geometry}
        material={materials.blinn2SG}
        position={[-4.63, 47.387, 17.587]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell.geometry}
        material={materials.blinn2SG}
        position={[2.875, 44.026, 15.208]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell001.geometry}
        material={materials.blinn2SG}
        position={[-2.318, 42.303, 18.816]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell002.geometry}
        material={materials.blinn2SG}
        position={[2.466, 43.569, 17.518]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell003.geometry}
        material={materials.blinn2SG}
        position={[-1.127, 41.235, 19.55]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell004.geometry}
        material={materials.blinn2SG}
        position={[-0.184, 41.359, 19.043]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell005.geometry}
        material={materials.blinn2SG}
        position={[2.456, 42.961, 16.474]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell006.geometry}
        material={materials.blinn2SG}
        position={[1.152, 44.742, 19.319]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell008_cell001_cell007.geometry}
        material={materials.blinn2SG}
        position={[-1.404, 42.337, 17.356]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell002_cell.geometry}
        material={materials.blinn2SG}
        position={[-8.093, -3.839, 12.694]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell002_cell001.geometry}
        material={materials.blinn2SG}
        position={[-8.748, -3.82, 11.868]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell002_cell002.geometry}
        material={materials.blinn2SG}
        position={[-8.838, -3.121, 12.86]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell013_cell002_cell003.geometry}
        material={materials.blinn2SG}
        position={[-1.786, 0.036, 12.735]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell003_cell.geometry}
        material={materials.blinn2SG}
        position={[6.919, -29.394, 16.783]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell003_cell001.geometry}
        material={materials.blinn2SG}
        position={[6.889, -29.785, 17.612]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell003_cell002.geometry}
        material={materials.blinn2SG}
        position={[6.585, -29.656, 16.952]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell003_cell003.geometry}
        material={materials.blinn2SG}
        position={[6.568, -29.622, 16.943]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell018_cell003_cell004.geometry}
        material={materials.blinn2SG}
        position={[6.864, -30.942, 16.377]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell.geometry}
        material={materials.blinn2SG}
        position={[-2.61, 25.026, 15.949]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell001.geometry}
        material={materials.blinn2SG}
        position={[-0.041, 23.417, 14.541]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell002.geometry}
        material={materials.blinn2SG}
        position={[-7.826, 22.323, 12.382]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell003.geometry}
        material={materials.blinn2SG}
        position={[-7.001, 23.281, 15.48]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell004.geometry}
        material={materials.blinn2SG}
        position={[-7.254, 22.892, 14.323]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell005.geometry}
        material={materials.blinn2SG}
        position={[-5.043, 24.147, 15.069]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell006.geometry}
        material={materials.blinn2SG}
        position={[-0.049, 24.779, 12.457]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell023_cell006_cell007.geometry}
        material={materials.blinn2SG}
        position={[0.059, 23.775, 13.562]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell.geometry}
        material={materials.blinn2SG}
        position={[2.921, -30.398, 19.455]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell001.geometry}
        material={materials.blinn2SG}
        position={[-1.995, -31.194, 20.227]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell002.geometry}
        material={materials.blinn2SG}
        position={[3.16, -32.72, 21.414]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell003.geometry}
        material={materials.blinn2SG}
        position={[1.312, -28.276, 19.213]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell006.geometry}
        material={materials.blinn2SG}
        position={[-1.191, -29.586, 20.072]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell.geometry}
        material={materials.blinn2SG}
        position={[-2.452, -33.041, 20.453]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell001.geometry}
        material={materials.blinn2SG}
        position={[-6.96, -27.068, 9.044]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell002.geometry}
        material={materials.blinn2SG}
        position={[-7.322, -16.669, 12.503]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell003.geometry}
        material={materials.blinn2SG}
        position={[-6.598, -23.097, 11.403]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell005.geometry}
        material={materials.blinn2SG}
        position={[-0.379, -25.833, 18.756]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell006.geometry}
        material={materials.blinn2SG}
        position={[1.411, -30.044, 17.294]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell007.geometry}
        material={materials.blinn2SG}
        position={[0.898, -26.76, 19.676]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell001.geometry}
        material={materials.blinn2SG}
        position={[-6.917, 41.413, 12.096]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell003.geometry}
        material={materials.blinn2SG}
        position={[-7.217, 37.513, 7.624]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell007.geometry}
        material={materials.blinn2SG}
        position={[-6.973, 36.368, 8.017]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell.geometry}
        material={materials.blinn2SG}
        position={[7.991, 27.472, 2.689]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell001.geometry}
        material={materials.blinn2SG}
        position={[11.247, 19.765, -5.009]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell002.geometry}
        material={materials.blinn2SG}
        position={[7.841, 29.326, 3.737]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell003.geometry}
        material={materials.blinn2SG}
        position={[6.263, 27.395, 1.387]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell004.geometry}
        material={materials.blinn2SG}
        position={[10.179, 31.318, 0.375]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell005.geometry}
        material={materials.blinn2SG}
        position={[1.901, 33.685, -0.331]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell006.geometry}
        material={materials.blinn2SG}
        position={[9.477, 23.944, 2.058]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell025_cell007.geometry}
        material={materials.blinn2SG}
        position={[8.612, 37.64, 1.626]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell.geometry}
        material={materials.blinn2SG}
        position={[5.459, 26.35, 9.282]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell002.geometry}
        material={materials.blinn2SG}
        position={[11.718, 24.044, 0.853]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell004.geometry}
        material={materials.blinn2SG}
        position={[7.057, 24.886, 3.622]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell005.geometry}
        material={materials.blinn2SG}
        position={[3.44, 31.671, 19.381]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell001.geometry}
        material={materials.blinn2SG}
        position={[9.306, -8.13, 6.207]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell003.geometry}
        material={materials.blinn2SG}
        position={[10.211, 2.374, 11.088]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell004.geometry}
        material={materials.blinn2SG}
        position={[11.35, 0.648, 7.886]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell005.geometry}
        material={materials.blinn2SG}
        position={[9.317, 0.378, -1.748]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell007.geometry}
        material={materials.blinn2SG}
        position={[7.717, 3.804, 5.156]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell.geometry}
        material={materials.blinn2SG}
        position={[-2.053, -3.346, -6.973]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell002.geometry}
        material={materials.blinn2SG}
        position={[14.526, -0.594, 0.752]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell003.geometry}
        material={materials.blinn2SG}
        position={[0.508, 2.536, -7.815]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell004.geometry}
        material={materials.blinn2SG}
        position={[-9.686, 26.541, 7.401]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell005.geometry}
        material={materials.blinn2SG}
        position={[-8.968, 26.236, 9.379]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell006.geometry}
        material={materials.blinn2SG}
        position={[11.318, -4.24, 3.289]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell007.geometry}
        material={materials.blinn2SG}
        position={[7.316, 32.352, 8.21]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell.geometry}
        material={materials.blinn2SG}
        position={[4.123, -34.066, 21.141]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell002.geometry}
        material={materials.blinn2SG}
        position={[5.082, -30.974, 18.182]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell003.geometry}
        material={materials.blinn2SG}
        position={[6.334, -29.266, 18.263]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell006.geometry}
        material={materials.blinn2SG}
        position={[0.652, -29.196, 20.789]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell007.geometry}
        material={materials.blinn2SG}
        position={[4.866, -30.815, 16.798]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell.geometry}
        material={materials.blinn2SG}
        position={[6.181, -29.526, 16.803]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell001.geometry}
        material={materials.blinn2SG}
        position={[7.146, -28.85, 16.431]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell002.geometry}
        material={materials.blinn2SG}
        position={[7.187, -27.999, 17.391]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell003.geometry}
        material={materials.blinn2SG}
        position={[6.354, -28.711, 16.475]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell004.geometry}
        material={materials.blinn2SG}
        position={[6.924, -28.567, 17.914]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell005.geometry}
        material={materials.blinn2SG}
        position={[6.907, -26.131, 17.784]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell004_cell006.geometry}
        material={materials.blinn2SG}
        position={[6.644, -29.919, 16.507]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell.geometry}
        material={materials.blinn2SG}
        position={[3.439, -27.539, 19.125]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell001.geometry}
        material={materials.blinn2SG}
        position={[2.531, -29.175, 18.528]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell002.geometry}
        material={materials.blinn2SG}
        position={[6.768, -29.238, 17.19]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell003.geometry}
        material={materials.blinn2SG}
        position={[5.709, -30.147, 17.147]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell004.geometry}
        material={materials.blinn2SG}
        position={[7.478, -28.749, 16.547]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell006.geometry}
        material={materials.blinn2SG}
        position={[2.702, -27.38, 18.146]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell001_cell001_cell007.geometry}
        material={materials.blinn2SG}
        position={[5.021, -29.994, 17.085]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell.geometry}
        material={materials.blinn2SG}
        position={[8.335, 6.412, 10.404]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell001.geometry}
        material={materials.blinn2SG}
        position={[4.291, -0.032, 4.913]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell002.geometry}
        material={materials.blinn2SG}
        position={[0.743, 5.901, 7.862]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell003.geometry}
        material={materials.blinn2SG}
        position={[-5.703, 9.746, 5.555]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell004.geometry}
        material={materials.blinn2SG}
        position={[-8.824, 7.956, 6.536]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell005.geometry}
        material={materials.blinn2SG}
        position={[-2.722, 13.181, 14.707]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell012_cell001_cell007.geometry}
        material={materials.blinn2SG}
        position={[8.485, 18.732, 5.008]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell.geometry}
        material={materials.blinn2SG}
        position={[7.026, -3.507, 2.632]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell001.geometry}
        material={materials.blinn2SG}
        position={[1.65, -3.562, 6.279]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell002.geometry}
        material={materials.blinn2SG}
        position={[5.952, 0.617, -1.049]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell003.geometry}
        material={materials.blinn2SG}
        position={[2.395, -6.64, 4.838]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell004.geometry}
        material={materials.blinn2SG}
        position={[-1.481, -0.341, 3.719]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell005.geometry}
        material={materials.blinn2SG}
        position={[8.093, -1.909, 2.174]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell006.geometry}
        material={materials.blinn2SG}
        position={[-0.718, -0.755, 0.508]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell006_cell007.geometry}
        material={materials.blinn2SG}
        position={[3.446, 1.825, 1.824]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell.geometry}
        material={materials.blinn2SG}
        position={[8.39, 1.665, 9.131]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell001.geometry}
        material={materials.blinn2SG}
        position={[7.638, 0.906, 11.996]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell002.geometry}
        material={materials.blinn2SG}
        position={[0.117, -5.051, 5.39]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell003.geometry}
        material={materials.blinn2SG}
        position={[1.799, -3.998, 10.125]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell004.geometry}
        material={materials.blinn2SG}
        position={[5.522, 3.449, 11.913]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell005.geometry}
        material={materials.blinn2SG}
        position={[5.836, 3.644, 11.888]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell006.geometry}
        material={materials.blinn2SG}
        position={[-0.866, 2.791, 4.12]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell002_cell007.geometry}
        material={materials.blinn2SG}
        position={[4.628, -2.409, 8.067]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell.geometry}
        material={materials.blinn2SG}
        position={[0.912, -11.546, 17.377]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell001.geometry}
        material={materials.blinn2SG}
        position={[1.384, -2.021, 4.493]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell002.geometry}
        material={materials.blinn2SG}
        position={[-9.031, -5.868, 9.64]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell003.geometry}
        material={materials.blinn2SG}
        position={[-1.212, 1.125, 6.43]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell004.geometry}
        material={materials.blinn2SG}
        position={[1.426, -2.073, 6.544]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell005.geometry}
        material={materials.blinn2SG}
        position={[-10.425, -4.52, 10.57]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell006.geometry}
        material={materials.blinn2SG}
        position={[2.008, -1.632, 6.815]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell020_cell_cell007.geometry}
        material={materials.blinn2SG}
        position={[-4.645, -1.356, 3.786]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell.geometry}
        material={materials.blinn2SG}
        position={[0.256, 25.762, 8.023]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell001.geometry}
        material={materials.blinn2SG}
        position={[-0.199, 24.797, 8.936]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell002.geometry}
        material={materials.blinn2SG}
        position={[3.33, 24.379, 5.862]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell003.geometry}
        material={materials.blinn2SG}
        position={[4.05, 27.026, 5.226]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell004.geometry}
        material={materials.blinn2SG}
        position={[0.478, 26.296, 8.264]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell007_cell005.geometry}
        material={materials.blinn2SG}
        position={[3.609, 26.607, 3.976]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell.geometry}
        material={materials.blinn2SG}
        position={[9.249, 26.49, 2.481]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell001.geometry}
        material={materials.blinn2SG}
        position={[8.75, 27.094, 5.742]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell002.geometry}
        material={materials.blinn2SG}
        position={[7.784, 28.259, 6.737]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell004.geometry}
        material={materials.blinn2SG}
        position={[9.066, 28.345, 3.881]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell005.geometry}
        material={materials.blinn2SG}
        position={[7.029, 27.399, 5.907]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell006.geometry}
        material={materials.blinn2SG}
        position={[7.571, 27.233, 2.238]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell003_cell007.geometry}
        material={materials.blinn2SG}
        position={[8.719, 27.562, 5.587]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell.geometry}
        material={materials.blinn2SG}
        position={[-1.63, 23.53, 13.276]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell001.geometry}
        material={materials.blinn2SG}
        position={[12.704, 17.427, 8.54]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell002.geometry}
        material={materials.blinn2SG}
        position={[8.595, 28.04, 13.59]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell003.geometry}
        material={materials.blinn2SG}
        position={[10.13, 11.855, 10]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell005.geometry}
        material={materials.blinn2SG}
        position={[0.312, 23.501, 15.739]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell006.geometry}
        material={materials.blinn2SG}
        position={[2.437, 24.019, 16.707]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell022_cell001_cell007.geometry}
        material={materials.blinn2SG}
        position={[11.241, 23.473, 12.908]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell.geometry}
        material={materials.blinn2SG}
        position={[-6.985, 39.657, 5.469]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell001.geometry}
        material={materials.blinn2SG}
        position={[-7.02, 42.613, 8.372]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell002.geometry}
        material={materials.blinn2SG}
        position={[-5.377, 41.155, 7.767]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell003.geometry}
        material={materials.blinn2SG}
        position={[-6.909, 39.893, 5.336]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell004.geometry}
        material={materials.blinn2SG}
        position={[-5.826, 39.733, 6.338]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell005.geometry}
        material={materials.blinn2SG}
        position={[-8.001, 41.248, 8.301]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell006.geometry}
        material={materials.blinn2SG}
        position={[-6.734, 43.622, 8.222]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell006_cell007.geometry}
        material={materials.blinn2SG}
        position={[-7.952, 41.406, 8.037]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell.geometry}
        material={materials.blinn2SG}
        position={[-8.065, 39.525, 4.255]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell001.geometry}
        material={materials.blinn2SG}
        position={[-7.312, 40.301, 6.33]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell002.geometry}
        material={materials.blinn2SG}
        position={[-6.966, 39.821, 5.324]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell003.geometry}
        material={materials.blinn2SG}
        position={[-8.189, 40.462, 5.246]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell004.geometry}
        material={materials.blinn2SG}
        position={[-7.189, 39.782, 5.171]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell005_cell005.geometry}
        material={materials.blinn2SG}
        position={[-8.833, 38.335, 6.346]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell.geometry}
        material={materials.blinn2SG}
        position={[-6.611, 42.769, 11.32]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell001.geometry}
        material={materials.blinn2SG}
        position={[-6.441, 41.843, 11.632]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell002.geometry}
        material={materials.blinn2SG}
        position={[-5.583, 44.34, 8.437]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell003.geometry}
        material={materials.blinn2SG}
        position={[-5.902, 40.761, 9.209]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell004.geometry}
        material={materials.blinn2SG}
        position={[-5.978, 41.058, 10.745]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell005.geometry}
        material={materials.blinn2SG}
        position={[-7.181, 44.158, 8.877]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell006.geometry}
        material={materials.blinn2SG}
        position={[-8.818, 42.029, 8.252]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell028_cell002_cell007.geometry}
        material={materials.blinn2SG}
        position={[-6.677, 42.688, 8.855]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell001.geometry}
        material={materials.blinn2SG}
        position={[-7.029, -29.502, 17.697]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell002.geometry}
        material={materials.blinn2SG}
        position={[-7.337, -24.766, 18.524]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell003.geometry}
        material={materials.blinn2SG}
        position={[-7.071, -32.577, 16.855]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell004.geometry}
        material={materials.blinn2SG}
        position={[-8.09, -26.948, 13.133]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell005.geometry}
        material={materials.blinn2SG}
        position={[-6.727, -27.793, 18.101]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell006.geometry}
        material={materials.blinn2SG}
        position={[-4.476, -29.404, 15.489]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell033_cell004_cell007.geometry}
        material={materials.blinn2SG}
        position={[-6.844, -32.06, 15.048]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell001.geometry}
        material={materials.blinn2SG}
        position={[0.551, -30.771, 20.082]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell002.geometry}
        material={materials.blinn2SG}
        position={[-0.126, -29.599, 20.354]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell003.geometry}
        material={materials.blinn2SG}
        position={[0.003, -29.823, 20.516]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell004.geometry}
        material={materials.blinn2SG}
        position={[1.277, -28.576, 19.915]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell005.geometry}
        material={materials.blinn2SG}
        position={[1.353, -29.284, 19.876]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell006.geometry}
        material={materials.blinn2SG}
        position={[0.977, -30.913, 20.209]}
      />
      <mesh
        geometry={nodes.pasted__pCube11_group_cell034_cell005_cell007.geometry}
        material={materials.blinn2SG}
        position={[-0.158, -29.341, 20.199]}
      />
      {/* <mesh geometry={nodes.origin_1.geometry} material={materials.blinn10SG} />
      <mesh geometry={nodes.origin_2.geometry} material={materials.blinn2SG} /> */}
    </group>
  );
}

useGLTF.preload("/models/banana.glb");
