/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/fuckoff.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useExplode } from "../hooks/useExplode";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/fuckoff.glb");

  const group = React.useRef();

  useExplode(group, { distance: 50 });

  // useEffect(() => {
  //   const groupWorldPosition = new THREE.Vector3();
  //   group.current.getWorldPosition(groupWorldPosition);

  //   group.current.children.forEach((mesh) => {
  //     mesh.originalPosition = mesh.position.clone();
  //     const meshWorldPosition = new THREE.Vector3();
  //     mesh.getWorldPosition(meshWorldPosition);

  //     mesh.directionalVector = meshWorldPosition
  //       .clone()
  //       .sub(groupWorldPosition)
  //       .normalize();
  //     mesh.targetPosition = mesh.originalPosition
  //       .clone()
  //       .add(mesh.directionalVector.clone().multiplyScalar(50));
  //   });
  // }, []);

  // const scrollData = useScroll();

  // useFrame(() => {
  //   group.current.children.forEach((mesh) => {
  //     mesh.position.x = THREE.MathUtils.lerp(
  //       mesh.originalPosition.x,
  //       mesh.targetPosition.x,
  //       scrollData.offset // 0 at the beginning, 1 after scroll
  //     );

  //     mesh.position.y = THREE.MathUtils.lerp(
  //       mesh.originalPosition.y,
  //       mesh.targetPosition.y,
  //       scrollData.offset // 0 at the beginning, 1 after scroll
  //     );

  //     mesh.position.z = THREE.MathUtils.lerp(
  //       mesh.originalPosition.z,
  //       mesh.targetPosition.z,
  //       scrollData.offset // 0 at the beginning, 1 after scroll
  //     );
  //   });
  // });

  return (
    <group {...props} dispose={null} ref={group}>
      {/* <mesh
        geometry={nodes.origin.geometry}
        material={nodes.origin.material}
        scale={55.01}
      /> */}
      <group position={[-1.607, -43.981, -21.207]}>
        <mesh
          geometry={nodes.Icosphere_cell040.geometry}
          material={nodes.Icosphere_cell040.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell040_1.geometry}
          material={nodes.Icosphere_cell040_1.material}
        />
      </group>
      <group position={[8.003, -52.021, 41.57]}>
        <mesh
          geometry={nodes.Icosphere_cell001.geometry}
          material={nodes.Icosphere_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_1.geometry}
          material={nodes.Icosphere_cell001_1.material}
        />
      </group>
      <group position={[-48.876, -25.265, 5.429]}>
        <mesh
          geometry={nodes.Icosphere_cell002_1.geometry}
          material={nodes.Icosphere_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell002_2.geometry}
          material={nodes.Icosphere_cell002_2.material}
        />
      </group>
      <group position={[20.926, -27.695, -53.683]}>
        <mesh
          geometry={nodes.Icosphere_cell003_1.geometry}
          material={nodes.Icosphere_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell003_2.geometry}
          material={nodes.Icosphere_cell003_2.material}
        />
      </group>
      <group position={[69.489, 24.24, 2.58]}>
        <mesh
          geometry={nodes.Icosphere_cell008.geometry}
          material={nodes.Icosphere_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_1.geometry}
          material={nodes.Icosphere_cell008_1.material}
        />
      </group>
      <group position={[0.05, 54.697, 0.09]}>
        <mesh
          geometry={nodes.Icosphere_cell009.geometry}
          material={nodes.Icosphere_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell009_1.geometry}
          material={nodes.Icosphere_cell009_1.material}
        />
      </group>
      <group position={[-27.775, -21.046, 24.345]}>
        <mesh
          geometry={nodes.Icosphere_cell013.geometry}
          material={nodes.Icosphere_cell013.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell013_1.geometry}
          material={nodes.Icosphere_cell013_1.material}
        />
      </group>
      <group position={[-16.749, -48.064, -44.654]}>
        <mesh
          geometry={nodes.Icosphere_cell014.geometry}
          material={nodes.Icosphere_cell014.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell014_1.geometry}
          material={nodes.Icosphere_cell014_1.material}
        />
      </group>
      <group position={[-36.799, -43.858, -33.862]}>
        <mesh
          geometry={nodes.Icosphere_cell015.geometry}
          material={nodes.Icosphere_cell015.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_1.geometry}
          material={nodes.Icosphere_cell015_1.material}
        />
      </group>
      <group position={[9.559, -26.818, -42.479]}>
        <mesh
          geometry={nodes.Icosphere_cell016.geometry}
          material={nodes.Icosphere_cell016.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_1.geometry}
          material={nodes.Icosphere_cell016_1.material}
        />
      </group>
      <group position={[53.211, -3.659, 18.217]}>
        <mesh
          geometry={nodes.Icosphere_cell017_1.geometry}
          material={nodes.Icosphere_cell017_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell017_2.geometry}
          material={nodes.Icosphere_cell017_2.material}
        />
      </group>
      <group position={[58.161, -34.504, -21.335]}>
        <mesh
          geometry={nodes.Icosphere_cell018_1.geometry}
          material={nodes.Icosphere_cell018_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell018_2.geometry}
          material={nodes.Icosphere_cell018_2.material}
        />
      </group>
      <group position={[15.773, -0.414, 45.863]}>
        <mesh
          geometry={nodes.Icosphere_cell019_1.geometry}
          material={nodes.Icosphere_cell019_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell019_2.geometry}
          material={nodes.Icosphere_cell019_2.material}
        />
      </group>
      <group position={[-49.705, -4.01, -65.146]}>
        <mesh
          geometry={nodes.Icosphere_cell021_1.geometry}
          material={nodes.Icosphere_cell021_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell021_2.geometry}
          material={nodes.Icosphere_cell021_2.material}
        />
      </group>
      <group position={[-43.682, -1.202, -15.601]}>
        <mesh
          geometry={nodes.Icosphere_cell022_1.geometry}
          material={nodes.Icosphere_cell022_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell022_2.geometry}
          material={nodes.Icosphere_cell022_2.material}
        />
      </group>
      <group position={[-31.783, 50.196, 11.313]}>
        <mesh
          geometry={nodes.Icosphere_cell027_1.geometry}
          material={nodes.Icosphere_cell027_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell027_2.geometry}
          material={nodes.Icosphere_cell027_2.material}
        />
      </group>
      <group position={[-13.449, 28.548, -39.747]}>
        <mesh
          geometry={nodes.Icosphere_cell028_1.geometry}
          material={nodes.Icosphere_cell028_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell028_2.geometry}
          material={nodes.Icosphere_cell028_2.material}
        />
      </group>
      <group position={[15.675, 24.089, -33.894]}>
        <mesh
          geometry={nodes.Icosphere_cell029.geometry}
          material={nodes.Icosphere_cell029.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_1.geometry}
          material={nodes.Icosphere_cell029_1.material}
        />
      </group>
      <group position={[-23.53, 47.466, 17.83]}>
        <mesh
          geometry={nodes.Icosphere_cell031.geometry}
          material={nodes.Icosphere_cell031.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_1.geometry}
          material={nodes.Icosphere_cell031_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell030_cell002.geometry}
        material={nodes.Icosphere_cell030_cell002.material}
        position={[-15.532, 6.472, 3.003]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell003.geometry}
        material={nodes.Icosphere_cell030_cell003.material}
        position={[16.136, -13.036, -31.625]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell005.geometry}
        material={nodes.Icosphere_cell030_cell005.material}
        position={[3.812, 9.169, -1.461]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell006.geometry}
        material={nodes.Icosphere_cell030_cell006.material}
        position={[-1.847, 19.538, -29.447]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell007.geometry}
        material={nodes.Icosphere_cell030_cell007.material}
        position={[47.065, -7.952, -11.421]}
      />
      <group position={[29.294, 15.968, -35.675]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell008.geometry}
          material={nodes.Icosphere_cell029_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell008_1.geometry}
          material={nodes.Icosphere_cell029_cell008_1.material}
        />
      </group>
      <group position={[29.379, 19.02, -46.2]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell009.geometry}
          material={nodes.Icosphere_cell029_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell009_1.geometry}
          material={nodes.Icosphere_cell029_cell009_1.material}
        />
      </group>
      <group position={[43.491, 2.804, -30.673]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell001_1.geometry}
          material={nodes.Icosphere_cell029_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell001_2.geometry}
          material={nodes.Icosphere_cell029_cell001_2.material}
        />
      </group>
      <group position={[36.967, -16.796, -29.618]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003.geometry}
          material={nodes.Icosphere_cell029_cell003.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_1.geometry}
          material={nodes.Icosphere_cell029_cell003_1.material}
        />
      </group>
      <group position={[13.299, 4.471, -44.938]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell004_1.geometry}
          material={nodes.Icosphere_cell029_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell004_2.geometry}
          material={nodes.Icosphere_cell029_cell004_2.material}
        />
      </group>
      <group position={[-9.56, -2.952, 48.19]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell009.geometry}
          material={nodes.Icosphere_cell026_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell009_1.geometry}
          material={nodes.Icosphere_cell026_cell009_1.material}
        />
      </group>
      <group position={[-19.386, 20.787, 42.253]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell003.geometry}
          material={nodes.Icosphere_cell026_cell003.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell003_1.geometry}
          material={nodes.Icosphere_cell026_cell003_1.material}
        />
      </group>
      <group position={[-47.612, -6.906, 26.023]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell004_1.geometry}
          material={nodes.Icosphere_cell026_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell004_2.geometry}
          material={nodes.Icosphere_cell026_cell004_2.material}
        />
      </group>
      <group position={[-45.84, -9.011, 24.455]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell005_1.geometry}
          material={nodes.Icosphere_cell026_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell005_2.geometry}
          material={nodes.Icosphere_cell026_cell005_2.material}
        />
      </group>
      <group position={[-30.285, 0.936, 40.833]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell006_1.geometry}
          material={nodes.Icosphere_cell026_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell006_2.geometry}
          material={nodes.Icosphere_cell026_cell006_2.material}
        />
      </group>
      <group position={[30.93, -28.389, -24.311]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell008.geometry}
          material={nodes.Icosphere_cell015_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell008_1.geometry}
          material={nodes.Icosphere_cell015_cell008_1.material}
        />
      </group>
      <group position={[17.271, -38.047, 19.053]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001.geometry}
          material={nodes.Icosphere_cell015_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_1.geometry}
          material={nodes.Icosphere_cell015_cell001_1.material}
        />
      </group>
      <group position={[18.551, -40.51, -19.821]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell003.geometry}
          material={nodes.Icosphere_cell015_cell003.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell003_1.geometry}
          material={nodes.Icosphere_cell015_cell003_1.material}
        />
      </group>
      <group position={[13.231, -48.139, 10.172]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004.geometry}
          material={nodes.Icosphere_cell015_cell004.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_1.geometry}
          material={nodes.Icosphere_cell015_cell004_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell013_cell002.geometry}
        material={nodes.Icosphere_cell013_cell002.material}
        position={[37.571, -12.175, -0.606]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell003.geometry}
        material={nodes.Icosphere_cell013_cell003.material}
        position={[17.186, -31.705, -36.567]}
      />
      <group position={[-9.011, -51.562, 2.135]}>
        <mesh
          geometry={nodes.Icosphere_cell013_cell003_1.geometry}
          material={nodes.Icosphere_cell013_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell013_cell003_2.geometry}
          material={nodes.Icosphere_cell013_cell003_2.material}
        />
      </group>
      <group position={[7.534, -56.031, 21.505]}>
        <mesh
          geometry={nodes.Icosphere_cell013_cell004_1.geometry}
          material={nodes.Icosphere_cell013_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell013_cell004_2.geometry}
          material={nodes.Icosphere_cell013_cell004_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell013_cell006.geometry}
        material={nodes.Icosphere_cell013_cell006.material}
        position={[-15.4, -5.482, 9.151]}
      />
      <group position={[-4.62, -52.02, 9.139]}>
        <mesh
          geometry={nodes.Icosphere_cell013_cell006_1.geometry}
          material={nodes.Icosphere_cell013_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell013_cell006_2.geometry}
          material={nodes.Icosphere_cell013_cell006_2.material}
        />
      </group>
      <group position={[-44.678, 20.947, 6.977]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell008.geometry}
          material={nodes.Icosphere_cell007_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell008_1.geometry}
          material={nodes.Icosphere_cell007_cell008_1.material}
        />
      </group>
      <group position={[-42.244, 7.202, 23.736]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell001.geometry}
          material={nodes.Icosphere_cell007_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell001_1.geometry}
          material={nodes.Icosphere_cell007_cell001_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell007_cell003.geometry}
        material={nodes.Icosphere_cell007_cell003.material}
        position={[-13.912, 7.652, 22.576]}
      />
      <group position={[-26.241, 31.565, 29.858]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell003_1.geometry}
          material={nodes.Icosphere_cell007_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell003_2.geometry}
          material={nodes.Icosphere_cell007_cell003_2.material}
        />
      </group>
      <group position={[-33.907, 34.618, 16.897]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell004_1.geometry}
          material={nodes.Icosphere_cell007_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell004_2.geometry}
          material={nodes.Icosphere_cell007_cell004_2.material}
        />
      </group>
      <group position={[-35.78, 10.557, 35.293]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell005_1.geometry}
          material={nodes.Icosphere_cell007_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell005_2.geometry}
          material={nodes.Icosphere_cell007_cell005_2.material}
        />
      </group>
      <group position={[-2.62, 13.491, 49.482]}>
        <mesh
          geometry={nodes.Icosphere_cell006_cell008.geometry}
          material={nodes.Icosphere_cell006_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell006_cell008_1.geometry}
          material={nodes.Icosphere_cell006_cell008_1.material}
        />
      </group>
      <group position={[22.065, 42.406, 33.995]}>
        <mesh
          geometry={nodes.Icosphere_cell006_cell009.geometry}
          material={nodes.Icosphere_cell006_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell006_cell009_1.geometry}
          material={nodes.Icosphere_cell006_cell009_1.material}
        />
      </group>
      <group position={[26.938, 31.757, 25.84]}>
        <mesh
          geometry={nodes.Icosphere_cell006_cell001_1.geometry}
          material={nodes.Icosphere_cell006_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell006_cell001_2.geometry}
          material={nodes.Icosphere_cell006_cell001_2.material}
        />
      </group>
      <group position={[36.729, 17.311, 27.568]}>
        <mesh
          geometry={nodes.Icosphere_cell006_cell002_1.geometry}
          material={nodes.Icosphere_cell006_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell006_cell002_2.geometry}
          material={nodes.Icosphere_cell006_cell002_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell006_cell004.geometry}
        material={nodes.Icosphere_cell006_cell004.material}
        position={[-0.007, 5.256, 10.478]}
      />
      <mesh
        geometry={nodes.Icosphere_cell006_cell005.geometry}
        material={nodes.Icosphere_cell006_cell005.material}
        position={[26.296, 12.567, 26.059]}
      />
      <group position={[24.636, 9.579, 47.388]}>
        <mesh
          geometry={nodes.Icosphere_cell006_cell005_1.geometry}
          material={nodes.Icosphere_cell006_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell006_cell005_2.geometry}
          material={nodes.Icosphere_cell006_cell005_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell006_cell007.geometry}
        material={nodes.Icosphere_cell006_cell007.material}
        position={[32.024, 17.179, 22.69]}
      />
      <group position={[34.799, -9.124, -39.001]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell008.geometry}
          material={nodes.Icosphere_cell005_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell008_1.geometry}
          material={nodes.Icosphere_cell005_cell008_1.material}
        />
      </group>
      <group position={[54.039, 0.044, -14.947]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell009.geometry}
          material={nodes.Icosphere_cell005_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell009_1.geometry}
          material={nodes.Icosphere_cell005_cell009_1.material}
        />
      </group>
      <group position={[28.311, -16.252, -40.362]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell002.geometry}
          material={nodes.Icosphere_cell005_cell002.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell002_1.geometry}
          material={nodes.Icosphere_cell005_cell002_1.material}
        />
      </group>
      <group position={[38.838, 10.528, -30.562]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003.geometry}
          material={nodes.Icosphere_cell005_cell003.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_1.geometry}
          material={nodes.Icosphere_cell005_cell003_1.material}
        />
      </group>
      <group position={[49.809, -8.784, -12.59]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell004_1.geometry}
          material={nodes.Icosphere_cell005_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell004_2.geometry}
          material={nodes.Icosphere_cell005_cell004_2.material}
        />
      </group>
      <group position={[47.116, -4.049, -20.815]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell008.geometry}
          material={nodes.Icosphere_cell005_cell003_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell008_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell008_1.material}
        />
      </group>
      <group position={[38.743, -3.371, -27.488]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell001.geometry}
          material={nodes.Icosphere_cell005_cell003_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell001_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell001_1.material}
        />
      </group>
      <group position={[42.078, -0.479, -28.034]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell002_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell002_2.geometry}
          material={nodes.Icosphere_cell005_cell003_cell002_2.material}
        />
      </group>
      <group position={[46.379, 1.94, -29.515]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell003_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell003_2.geometry}
          material={nodes.Icosphere_cell005_cell003_cell003_2.material}
        />
      </group>
      <group position={[44.843, 3.274, -24.676]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell004_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell004_2.geometry}
          material={nodes.Icosphere_cell005_cell003_cell004_2.material}
        />
      </group>
      <group position={[50.387, -0.65, -18.967]}>
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell005_1.geometry}
          material={nodes.Icosphere_cell005_cell003_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell005_cell003_cell005_2.geometry}
          material={nodes.Icosphere_cell005_cell003_cell005_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell007_cell007_cell.geometry}
        material={nodes.Icosphere_cell007_cell007_cell.material}
        position={[-25.335, 11.209, 15.791]}
      />
      <mesh
        geometry={nodes.Icosphere_cell007_cell007_cell001.geometry}
        material={nodes.Icosphere_cell007_cell007_cell001.material}
        position={[-21.071, 24.732, 15.139]}
      />
      <group position={[-45.662, 25.238, 17.902]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell001_1.geometry}
          material={nodes.Icosphere_cell007_cell007_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell001_2.geometry}
          material={nodes.Icosphere_cell007_cell007_cell001_2.material}
        />
      </group>
      <group position={[-34.005, 31.829, 24.491]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell002_1.geometry}
          material={nodes.Icosphere_cell007_cell007_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell002_2.geometry}
          material={nodes.Icosphere_cell007_cell007_cell002_2.material}
        />
      </group>
      <group position={[-44.795, 24.894, 20.315]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell003.geometry}
          material={nodes.Icosphere_cell007_cell007_cell003.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell003_1.geometry}
          material={nodes.Icosphere_cell007_cell007_cell003_1.material}
        />
      </group>
      <group position={[-27.043, 22.178, 42.712]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell004_1.geometry}
          material={nodes.Icosphere_cell007_cell007_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell004_2.geometry}
          material={nodes.Icosphere_cell007_cell007_cell004_2.material}
        />
      </group>
      <group position={[-45.686, 20.762, 16.617]}>
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell005_1.geometry}
          material={nodes.Icosphere_cell007_cell007_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell007_cell007_cell005_2.geometry}
          material={nodes.Icosphere_cell007_cell007_cell005_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell.geometry}
        material={nodes.Icosphere_cell013_cell001_cell.material}
        position={[1.829, -32.116, 14.211]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell001.geometry}
        material={nodes.Icosphere_cell013_cell001_cell001.material}
        position={[7.389, -24.799, -1.511]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell002.geometry}
        material={nodes.Icosphere_cell013_cell001_cell002.material}
        position={[8.764, -13.528, 19.333]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell003.geometry}
        material={nodes.Icosphere_cell013_cell001_cell003.material}
        position={[25.665, -26.256, 17.485]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell004.geometry}
        material={nodes.Icosphere_cell013_cell001_cell004.material}
        position={[22.471, -11.384, 7.912]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell005.geometry}
        material={nodes.Icosphere_cell013_cell001_cell005.material}
        position={[-0.883, -12.94, 15.979]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell006.geometry}
        material={nodes.Icosphere_cell013_cell001_cell006.material}
        position={[14.596, -33.593, 33.879]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell001_cell007.geometry}
        material={nodes.Icosphere_cell013_cell001_cell007.material}
        position={[-0.941, -17.273, 3.902]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell.geometry}
        material={nodes.Icosphere_cell013_cell_cell.material}
        position={[11.923, -24.914, -8.573]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell001.geometry}
        material={nodes.Icosphere_cell013_cell_cell001.material}
        position={[-2.188, -7.77, -18.386]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell002.geometry}
        material={nodes.Icosphere_cell013_cell_cell002.material}
        position={[12.928, -13.304, -16.146]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell003.geometry}
        material={nodes.Icosphere_cell013_cell_cell003.material}
        position={[5.909, -21.382, 5.786]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell004.geometry}
        material={nodes.Icosphere_cell013_cell_cell004.material}
        position={[6.347, 0.977, 9.861]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell005.geometry}
        material={nodes.Icosphere_cell013_cell_cell005.material}
        position={[-3.802, -13.24, 5.352]}
      />
      <mesh
        geometry={nodes.Icosphere_cell013_cell_cell006.geometry}
        material={nodes.Icosphere_cell013_cell_cell006.material}
        position={[14.929, -5.203, 1.019]}
      />
      <group position={[36.479, -29.16, 21.115]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell007.geometry}
          material={nodes.Icosphere_cell015_cell004_cell007.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell007_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell007_1.material}
        />
      </group>
      <group position={[26.939, -29.628, -0.431]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell001_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell001_2.geometry}
          material={nodes.Icosphere_cell015_cell004_cell001_2.material}
        />
      </group>
      <group position={[29.534, -21.201, 0.627]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell002_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell002_2.geometry}
          material={nodes.Icosphere_cell015_cell004_cell002_2.material}
        />
      </group>
      <group position={[30.794, -42.833, 1.733]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell003_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell003_2.geometry}
          material={nodes.Icosphere_cell015_cell004_cell003_2.material}
        />
      </group>
      <group position={[26.703, -40.501, 20.962]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell004_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell004_2.geometry}
          material={nodes.Icosphere_cell015_cell004_cell004_2.material}
        />
      </group>
      <group position={[28.506, -34.255, 21.875]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell005_1.geometry}
          material={nodes.Icosphere_cell015_cell004_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell004_cell005_2.geometry}
          material={nodes.Icosphere_cell015_cell004_cell005_2.material}
        />
      </group>
      <group position={[21.869, -46.098, 18.482]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell008.geometry}
          material={nodes.Icosphere_cell015_cell001_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell008_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell008_1.material}
        />
      </group>
      <group position={[21.99, -47.14, 15.989]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell009.geometry}
          material={nodes.Icosphere_cell015_cell001_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell009_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell009_1.material}
        />
      </group>
      <group position={[24.588, -45.661, 14.48]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell001_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell001_2.geometry}
          material={nodes.Icosphere_cell015_cell001_cell001_2.material}
        />
      </group>
      <group position={[23.335, -47.584, 14.964]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell002_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell002_2.geometry}
          material={nodes.Icosphere_cell015_cell001_cell002_2.material}
        />
      </group>
      <group position={[25.73, -45.181, 15.564]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell003_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell003_2.geometry}
          material={nodes.Icosphere_cell015_cell001_cell003_2.material}
        />
      </group>
      <group position={[24.748, -44.948, 19.051]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell004_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell004_2.geometry}
          material={nodes.Icosphere_cell015_cell001_cell004_2.material}
        />
      </group>
      <group position={[23.357, -47.6, 17.126]}>
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell005.geometry}
          material={nodes.Icosphere_cell015_cell001_cell005.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell015_cell001_cell005_1.geometry}
          material={nodes.Icosphere_cell015_cell001_cell005_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell.geometry}
        material={nodes.Icosphere_cell026_cell003_cell.material}
        position={[-18.403, 8.02, 21.716]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell001.geometry}
        material={nodes.Icosphere_cell026_cell003_cell001.material}
        position={[-13.629, 13.661, 40.798]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell002.geometry}
        material={nodes.Icosphere_cell026_cell003_cell002.material}
        position={[-17.962, -4.93, 36.194]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell004.geometry}
        material={nodes.Icosphere_cell026_cell003_cell004.material}
        position={[-16.436, 9.47, 29.78]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell005.geometry}
        material={nodes.Icosphere_cell026_cell003_cell005.material}
        position={[-13.099, 4.606, 41.03]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell006.geometry}
        material={nodes.Icosphere_cell026_cell003_cell006.material}
        position={[-29.053, 8.298, 20.38]}
      />
      <mesh
        geometry={nodes.Icosphere_cell026_cell003_cell007.geometry}
        material={nodes.Icosphere_cell026_cell003_cell007.material}
        position={[-12.411, -7.646, 41.144]}
      />
      <group position={[-8.602, 7.682, 51.27]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell006.geometry}
          material={nodes.Icosphere_cell026_cell002_cell006.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell006_1.geometry}
          material={nodes.Icosphere_cell026_cell002_cell006_1.material}
        />
      </group>
      <group position={[-18.527, 8.117, 46.469]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell007.geometry}
          material={nodes.Icosphere_cell026_cell002_cell007.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell007_1.geometry}
          material={nodes.Icosphere_cell026_cell002_cell007_1.material}
        />
      </group>
      <group position={[-12.906, 10.235, 44.378]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell001_1.geometry}
          material={nodes.Icosphere_cell026_cell002_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell001_2.geometry}
          material={nodes.Icosphere_cell026_cell002_cell001_2.material}
        />
      </group>
      <group position={[-9.31, 8.283, 48.36]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell002_1.geometry}
          material={nodes.Icosphere_cell026_cell002_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell002_2.geometry}
          material={nodes.Icosphere_cell026_cell002_cell002_2.material}
        />
      </group>
      <group position={[-16.641, 13.055, 46.22]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell003_1.geometry}
          material={nodes.Icosphere_cell026_cell002_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell002_cell003_2.geometry}
          material={nodes.Icosphere_cell026_cell002_cell003_2.material}
        />
      </group>
      <group position={[-6.762, -10.926, 46.806]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell008.geometry}
          material={nodes.Icosphere_cell026_cell_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell008_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell008_1.material}
        />
      </group>
      <group position={[-23.663, -12.8, 45.139]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell001_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell001_2.geometry}
          material={nodes.Icosphere_cell026_cell_cell001_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell026_cell_cell003.geometry}
        material={nodes.Icosphere_cell026_cell_cell003.material}
        position={[-8.121, -8.407, 37.255]}
      />
      <group position={[-16.891, -21.991, 48.24]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell003_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell003_2.geometry}
          material={nodes.Icosphere_cell026_cell_cell003_2.material}
        />
      </group>
      <group position={[-17.748, -18.325, 47.924]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell004_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell004_2.geometry}
          material={nodes.Icosphere_cell026_cell_cell004_2.material}
        />
      </group>
      <group position={[-25.162, -15.613, 40.203]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell005_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell005_2.geometry}
          material={nodes.Icosphere_cell026_cell_cell005_2.material}
        />
      </group>
      <group position={[-10.845, -18.061, 51.007]}>
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell006_1.geometry}
          material={nodes.Icosphere_cell026_cell_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell026_cell_cell006_2.geometry}
          material={nodes.Icosphere_cell026_cell_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell.geometry}
        material={nodes.Icosphere_cell029_cell007_cell.material}
        position={[36.054, 0.566, -26.851]}
      />
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell001.geometry}
        material={nodes.Icosphere_cell029_cell007_cell001.material}
        position={[21.15, -7.051, -43.518]}
      />
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell002.geometry}
        material={nodes.Icosphere_cell029_cell007_cell002.material}
        position={[24.232, -9.037, -38.519]}
      />
      <group position={[32.759, 8.1, -42.224]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell007_cell002_1.geometry}
          material={nodes.Icosphere_cell029_cell007_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell007_cell002_2.geometry}
          material={nodes.Icosphere_cell029_cell007_cell002_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell004.geometry}
        material={nodes.Icosphere_cell029_cell007_cell004.material}
        position={[29.565, 1.699, -43.819]}
      />
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell005.geometry}
        material={nodes.Icosphere_cell029_cell007_cell005.material}
        position={[28.517, -3.986, -29.655]}
      />
      <mesh
        geometry={nodes.Icosphere_cell029_cell007_cell007.geometry}
        material={nodes.Icosphere_cell029_cell007_cell007.material}
        position={[20.159, 10.314, -34.744]}
      />
      <group position={[36.812, -6.227, -33.699]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell008.geometry}
          material={nodes.Icosphere_cell029_cell003_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell008_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell008_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell029_cell003_cell001.geometry}
        material={nodes.Icosphere_cell029_cell003_cell001.material}
        position={[27.331, 3.405, -42.975]}
      />
      <group position={[38.907, -1.935, -32.341]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell001_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell001_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell001_2.material}
        />
      </group>
      <group position={[28.524, 0.166, -45.899]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell002_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell002_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell002_2.material}
        />
      </group>
      <group position={[26.12, -15.813, -42.13]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell003_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell003_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell003_2.material}
        />
      </group>
      <group position={[35.417, 4.843, -38.163]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell004_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell004_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell004_2.material}
        />
      </group>
      <group position={[28.63, 3.781, -45.227]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell005_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell005_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell005_2.material}
        />
      </group>
      <group position={[33.267, 2.378, -42.661]}>
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell006_1.geometry}
          material={nodes.Icosphere_cell029_cell003_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell029_cell003_cell006_2.geometry}
          material={nodes.Icosphere_cell029_cell003_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell.geometry}
        material={nodes.Icosphere_cell030_cell001_cell.material}
        position={[25.81, 15.188, 5.416]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell001.geometry}
        material={nodes.Icosphere_cell030_cell001_cell001.material}
        position={[15.709, 15.13, -24.608]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell003.geometry}
        material={nodes.Icosphere_cell030_cell001_cell003.material}
        position={[25.462, -1.01, -20.507]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell004.geometry}
        material={nodes.Icosphere_cell030_cell001_cell004.material}
        position={[16.395, 8.112, -18.639]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell005.geometry}
        material={nodes.Icosphere_cell030_cell001_cell005.material}
        position={[7.196, 13.435, -13.323]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell006.geometry}
        material={nodes.Icosphere_cell030_cell001_cell006.material}
        position={[30.975, 14.447, 1.517]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell001_cell007.geometry}
        material={nodes.Icosphere_cell030_cell001_cell007.material}
        position={[15.164, 15.318, -20.157]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell.geometry}
        material={nodes.Icosphere_cell030_cell_cell.material}
        position={[7.203, -16.398, -16.703]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell002.geometry}
        material={nodes.Icosphere_cell030_cell_cell002.material}
        position={[14.381, 5.077, -25.538]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell003.geometry}
        material={nodes.Icosphere_cell030_cell_cell003.material}
        position={[8.027, 12.198, -21.253]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell004.geometry}
        material={nodes.Icosphere_cell030_cell_cell004.material}
        position={[24.906, 2.13, -12.07]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell005.geometry}
        material={nodes.Icosphere_cell030_cell_cell005.material}
        position={[-6.142, 6.282, -26.917]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell006.geometry}
        material={nodes.Icosphere_cell030_cell_cell006.material}
        position={[2.801, 6.088, -46.804]}
      />
      <mesh
        geometry={nodes.Icosphere_cell030_cell_cell007.geometry}
        material={nodes.Icosphere_cell030_cell_cell007.material}
        position={[-6.778, -4.626, -11.544]}
      />
      <mesh
        geometry={nodes.Icosphere_cell039_cell.geometry}
        material={nodes.Icosphere_cell039_cell.material}
        position={[50.213, 0.767, 2.081]}
      />
      <group position={[21.007, 32.416, -14.834]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell009.geometry}
          material={nodes.Icosphere_cell039_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell009_1.geometry}
          material={nodes.Icosphere_cell039_cell009_1.material}
        />
      </group>
      <group position={[40.308, 15.874, -6.005]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell001_1.geometry}
          material={nodes.Icosphere_cell039_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell001_2.geometry}
          material={nodes.Icosphere_cell039_cell001_2.material}
        />
      </group>
      <group position={[54.693, -4.091, -7.011]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell002_1.geometry}
          material={nodes.Icosphere_cell039_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell002_2.geometry}
          material={nodes.Icosphere_cell039_cell002_2.material}
        />
      </group>
      <group position={[41.283, -0.048, -29.415]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell003_1.geometry}
          material={nodes.Icosphere_cell039_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell003_2.geometry}
          material={nodes.Icosphere_cell039_cell003_2.material}
        />
      </group>
      <group position={[40.576, 9.647, -33.605]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell004_1.geometry}
          material={nodes.Icosphere_cell039_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell004_2.geometry}
          material={nodes.Icosphere_cell039_cell004_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell039_cell006.geometry}
        material={nodes.Icosphere_cell039_cell006.material}
        position={[31.452, 11.471, -9.674]}
      />
      <group position={[21.655, 27.744, -31.415]}>
        <mesh
          geometry={nodes.Icosphere_cell039_cell006_1.geometry}
          material={nodes.Icosphere_cell039_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell039_cell006_2.geometry}
          material={nodes.Icosphere_cell039_cell006_2.material}
        />
      </group>
      <group position={[-11.831, -1.993, -41.44]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell008.geometry}
          material={nodes.Icosphere_cell038_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell008_1.geometry}
          material={nodes.Icosphere_cell038_cell008_1.material}
        />
      </group>
      <group position={[-28.007, 41.144, -17.604]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell001.geometry}
          material={nodes.Icosphere_cell038_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell001_1.geometry}
          material={nodes.Icosphere_cell038_cell001_1.material}
        />
      </group>
      <group position={[-23.797, 9.108, -41.465]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell002_1.geometry}
          material={nodes.Icosphere_cell038_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell002_2.geometry}
          material={nodes.Icosphere_cell038_cell002_2.material}
        />
      </group>
      <group position={[-26.972, 38.034, -24.412]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell003_1.geometry}
          material={nodes.Icosphere_cell038_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell003_2.geometry}
          material={nodes.Icosphere_cell038_cell003_2.material}
        />
      </group>
      <group position={[-49.573, 17.131, -29.951]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell004_1.geometry}
          material={nodes.Icosphere_cell038_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell004_2.geometry}
          material={nodes.Icosphere_cell038_cell004_2.material}
        />
      </group>
      <group position={[-21.82, 4.911, -35.279]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell005_1.geometry}
          material={nodes.Icosphere_cell038_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell005_2.geometry}
          material={nodes.Icosphere_cell038_cell005_2.material}
        />
      </group>
      <group position={[-40.778, 25.852, -29.394]}>
        <mesh
          geometry={nodes.Icosphere_cell038_cell006_1.geometry}
          material={nodes.Icosphere_cell038_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell038_cell006_2.geometry}
          material={nodes.Icosphere_cell038_cell006_2.material}
        />
      </group>
      <group position={[40.835, 31.065, -4.518]}>
        <mesh
          geometry={nodes.Icosphere_cell036_cell008.geometry}
          material={nodes.Icosphere_cell036_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell036_cell008_1.geometry}
          material={nodes.Icosphere_cell036_cell008_1.material}
        />
      </group>
      <group position={[45.332, 20.681, 16.595]}>
        <mesh
          geometry={nodes.Icosphere_cell036_cell009.geometry}
          material={nodes.Icosphere_cell036_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell036_cell009_1.geometry}
          material={nodes.Icosphere_cell036_cell009_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell036_cell002.geometry}
        material={nodes.Icosphere_cell036_cell002.material}
        position={[1.033, 20.524, 24.843]}
      />
      <group position={[6.414, 48.514, 18.88]}>
        <mesh
          geometry={nodes.Icosphere_cell036_cell002_1.geometry}
          material={nodes.Icosphere_cell036_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell036_cell002_2.geometry}
          material={nodes.Icosphere_cell036_cell002_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell036_cell004.geometry}
        material={nodes.Icosphere_cell036_cell004.material}
        position={[15.489, 12.251, 10.824]}
      />
      <group position={[34.419, 31.088, 26.884]}>
        <mesh
          geometry={nodes.Icosphere_cell036_cell004_1.geometry}
          material={nodes.Icosphere_cell036_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell036_cell004_2.geometry}
          material={nodes.Icosphere_cell036_cell004_2.material}
        />
      </group>
      <group position={[30.957, 33.458, 4.818]}>
        <mesh
          geometry={nodes.Icosphere_cell036_cell005_1.geometry}
          material={nodes.Icosphere_cell036_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell036_cell005_2.geometry}
          material={nodes.Icosphere_cell036_cell005_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell036_cell007.geometry}
        material={nodes.Icosphere_cell036_cell007.material}
        position={[36.287, 9.828, 0.565]}
      />
      <group position={[-2.141, 55.566, 22]}>
        <mesh
          geometry={nodes.Icosphere_cell032_cell008.geometry}
          material={nodes.Icosphere_cell032_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell032_cell008_1.geometry}
          material={nodes.Icosphere_cell032_cell008_1.material}
        />
      </group>
      <group position={[-15.315, -0.762, 35.766]}>
        <mesh
          geometry={nodes.Icosphere_cell032_cell009.geometry}
          material={nodes.Icosphere_cell032_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell032_cell009_1.geometry}
          material={nodes.Icosphere_cell032_cell009_1.material}
        />
      </group>
      <group position={[-4.161, 25.779, 59.247]}>
        <mesh
          geometry={nodes.Icosphere_cell032_cell001_1.geometry}
          material={nodes.Icosphere_cell032_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell032_cell001_2.geometry}
          material={nodes.Icosphere_cell032_cell001_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell032_cell003.geometry}
        material={nodes.Icosphere_cell032_cell003.material}
        position={[-1.105, 4.974, 9.955]}
      />
      <group position={[-11.077, 35.285, 25.581]}>
        <mesh
          geometry={nodes.Icosphere_cell032_cell003_1.geometry}
          material={nodes.Icosphere_cell032_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell032_cell003_2.geometry}
          material={nodes.Icosphere_cell032_cell003_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell032_cell005.geometry}
        material={nodes.Icosphere_cell032_cell005.material}
        position={[-15.121, 17.526, 10.589]}
      />
      <group position={[-18.809, 34.8, 28.177]}>
        <mesh
          geometry={nodes.Icosphere_cell032_cell005_1.geometry}
          material={nodes.Icosphere_cell032_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell032_cell005_2.geometry}
          material={nodes.Icosphere_cell032_cell005_2.material}
        />
      </group>
      <group position={[42.5, 39.734, -8.853]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell008.geometry}
          material={nodes.Icosphere_cell031_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell008_1.geometry}
          material={nodes.Icosphere_cell031_cell008_1.material}
        />
      </group>
      <group position={[6.945, 48.009, -22.347]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell009.geometry}
          material={nodes.Icosphere_cell031_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell009_1.geometry}
          material={nodes.Icosphere_cell031_cell009_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell031_cell002.geometry}
        material={nodes.Icosphere_cell031_cell002.material}
        position={[-5.98, 41.508, 9.907]}
      />
      <group position={[13.729, 62.342, 17.972]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell002_1.geometry}
          material={nodes.Icosphere_cell031_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell002_2.geometry}
          material={nodes.Icosphere_cell031_cell002_2.material}
        />
      </group>
      <group position={[30.548, 45.498, 3.427]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell003_1.geometry}
          material={nodes.Icosphere_cell031_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell003_2.geometry}
          material={nodes.Icosphere_cell031_cell003_2.material}
        />
      </group>
      <group position={[8.27, 44.085, -24.966]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell004_1.geometry}
          material={nodes.Icosphere_cell031_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell004_2.geometry}
          material={nodes.Icosphere_cell031_cell004_2.material}
        />
      </group>
      <group position={[13.268, 46.912, -0.728]}>
        <mesh
          geometry={nodes.Icosphere_cell031_cell005_1.geometry}
          material={nodes.Icosphere_cell031_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell031_cell005_2.geometry}
          material={nodes.Icosphere_cell031_cell005_2.material}
        />
      </group>
      <group position={[-3.116, -54.336, 1.748]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell001.geometry}
          material={nodes.Icosphere_cell016_cell001.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_1.geometry}
          material={nodes.Icosphere_cell016_cell001_1.material}
        />
      </group>
      <group position={[-6.417, -50.673, 13.558]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell002_1.geometry}
          material={nodes.Icosphere_cell016_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell002_2.geometry}
          material={nodes.Icosphere_cell016_cell002_2.material}
        />
      </group>
      <group position={[-12.633, -32.633, -2.903]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell003_1.geometry}
          material={nodes.Icosphere_cell016_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell003_2.geometry}
          material={nodes.Icosphere_cell016_cell003_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell016_cell005.geometry}
        material={nodes.Icosphere_cell016_cell005.material}
        position={[-12.052, -41.25, 16.14]}
      />
      <group position={[-23.703, -32.703, -5.365]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell005_1.geometry}
          material={nodes.Icosphere_cell016_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell005_2.geometry}
          material={nodes.Icosphere_cell016_cell005_2.material}
        />
      </group>
      <group position={[-7.585, -48.466, 17.623]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell006_1.geometry}
          material={nodes.Icosphere_cell016_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell006_2.geometry}
          material={nodes.Icosphere_cell016_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell008_cell004.geometry}
        material={nodes.Icosphere_cell008_cell004.material}
        position={[-27.106, -1.161, 22.665]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell005.geometry}
        material={nodes.Icosphere_cell008_cell005.material}
        position={[-13.841, -15.863, -8.538]}
      />
      <group position={[-39.695, 30.663, -6.595]}>
        <mesh
          geometry={nodes.Icosphere_cell008_cell004_1.geometry}
          material={nodes.Icosphere_cell008_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_cell004_2.geometry}
          material={nodes.Icosphere_cell008_cell004_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell008_cell007.geometry}
        material={nodes.Icosphere_cell008_cell007.material}
        position={[-26.9, 8.608, 13.424]}
      />
      <group position={[30.969, -10.208, -4.696]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell009.geometry}
          material={nodes.Icosphere_cell001_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell009_1.geometry}
          material={nodes.Icosphere_cell001_cell009_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell002.geometry}
        material={nodes.Icosphere_cell001_cell002.material}
        position={[6.355, 6.524, 10.632]}
      />
      <group position={[28.585, -35.885, 49.377]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell002_1.geometry}
          material={nodes.Icosphere_cell001_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell002_2.geometry}
          material={nodes.Icosphere_cell001_cell002_2.material}
        />
      </group>
      <group position={[37.988, -7.271, -3.212]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell003_1.geometry}
          material={nodes.Icosphere_cell001_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell003_2.geometry}
          material={nodes.Icosphere_cell001_cell003_2.material}
        />
      </group>
      <group position={[15.987, -28.262, 39.353]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell005.geometry}
          material={nodes.Icosphere_cell001_cell005.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_1.geometry}
          material={nodes.Icosphere_cell001_cell005_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell007.geometry}
        material={nodes.Icosphere_cell001_cell007.material}
        position={[13.852, 26.728, 25.369]}
      />
      <mesh
        geometry={nodes.Icosphere_cell001_cell005_cell.geometry}
        material={nodes.Icosphere_cell001_cell005_cell.material}
        position={[31.211, 13.558, 8.17]}
      />
      <group position={[41.396, -28.364, 22.444]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell009.geometry}
          material={nodes.Icosphere_cell001_cell005_cell009.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell009_1.geometry}
          material={nodes.Icosphere_cell001_cell005_cell009_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell005_cell002.geometry}
        material={nodes.Icosphere_cell001_cell005_cell002.material}
        position={[24.463, 20.508, 21.158]}
      />
      <mesh
        geometry={nodes.Icosphere_cell001_cell005_cell003.geometry}
        material={nodes.Icosphere_cell001_cell005_cell003.material}
        position={[30.08, 11.536, 6.971]}
      />
      <mesh
        geometry={nodes.Icosphere_cell001_cell005_cell004.geometry}
        material={nodes.Icosphere_cell001_cell005_cell004.material}
        position={[29.667, 14.097, 8.04]}
      />
      <group position={[37.223, -18.675, 34.293]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell004_1.geometry}
          material={nodes.Icosphere_cell001_cell005_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell004_2.geometry}
          material={nodes.Icosphere_cell001_cell005_cell004_2.material}
        />
      </group>
      <group position={[34.666, -13.018, 35.336]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell005_1.geometry}
          material={nodes.Icosphere_cell001_cell005_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell005_2.geometry}
          material={nodes.Icosphere_cell001_cell005_cell005_2.material}
        />
      </group>
      <group position={[31.112, -6.273, 35.55]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell006_1.geometry}
          material={nodes.Icosphere_cell001_cell005_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell005_cell006_2.geometry}
          material={nodes.Icosphere_cell001_cell005_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell_cell001.geometry}
        material={nodes.Icosphere_cell001_cell_cell001.material}
        position={[23.571, -10.885, 20.777]}
      />
      <group position={[39.817, 10.455, 36.727]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell_cell001_1.geometry}
          material={nodes.Icosphere_cell001_cell_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell_cell001_2.geometry}
          material={nodes.Icosphere_cell001_cell_cell001_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell_cell004.geometry}
        material={nodes.Icosphere_cell001_cell_cell004.material}
        position={[25.348, 6.347, 21.185]}
      />
      <mesh
        geometry={nodes.Icosphere_cell001_cell_cell005.geometry}
        material={nodes.Icosphere_cell001_cell_cell005.material}
        position={[25.306, 9.276, 24.883]}
      />
      <group position={[28.506, -14.971, 47.288]}>
        <mesh
          geometry={nodes.Icosphere_cell001_cell_cell004_1.geometry}
          material={nodes.Icosphere_cell001_cell_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell001_cell_cell004_2.geometry}
          material={nodes.Icosphere_cell001_cell_cell004_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell001_cell_cell007.geometry}
        material={nodes.Icosphere_cell001_cell_cell007.material}
        position={[17.833, -3.471, 22.501]}
      />
      <group position={[-51.783, 12.339, -12.75]}>
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell008.geometry}
          material={nodes.Icosphere_cell008_cell003_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell008_1.geometry}
          material={nodes.Icosphere_cell008_cell003_cell008_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell008_cell003_cell001.geometry}
        material={nodes.Icosphere_cell008_cell003_cell001.material}
        position={[-24.233, 28.757, -0.255]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell003_cell002.geometry}
        material={nodes.Icosphere_cell008_cell003_cell002.material}
        position={[-40.412, -2.726, -12.616]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell003_cell003.geometry}
        material={nodes.Icosphere_cell008_cell003_cell003.material}
        position={[-22.3, 29.09, 15.196]}
      />
      <group position={[-48.111, 35.74, -2.335]}>
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell003_1.geometry}
          material={nodes.Icosphere_cell008_cell003_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell003_2.geometry}
          material={nodes.Icosphere_cell008_cell003_cell003_2.material}
        />
      </group>
      <group position={[-37.399, -0.721, -7.013]}>
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell004_1.geometry}
          material={nodes.Icosphere_cell008_cell003_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell004_2.geometry}
          material={nodes.Icosphere_cell008_cell003_cell004_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell008_cell003_cell006.geometry}
        material={nodes.Icosphere_cell008_cell003_cell006.material}
        position={[-43.559, 8.924, -16.278]}
      />
      <group position={[-53.273, -2.164, 22.563]}>
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell006_1.geometry}
          material={nodes.Icosphere_cell008_cell003_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell008_cell003_cell006_2.geometry}
          material={nodes.Icosphere_cell008_cell003_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell001.geometry}
        material={nodes.Icosphere_cell008_cell001_cell001.material}
        position={[-17.994, -16.632, -27.842]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell002.geometry}
        material={nodes.Icosphere_cell008_cell001_cell002.material}
        position={[-14.743, 14.66, -18.596]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell003.geometry}
        material={nodes.Icosphere_cell008_cell001_cell003.material}
        position={[-19.268, -18.407, -26.667]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell004.geometry}
        material={nodes.Icosphere_cell008_cell001_cell004.material}
        position={[-28.623, -7.957, -28.217]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell005.geometry}
        material={nodes.Icosphere_cell008_cell001_cell005.material}
        position={[-11.269, 8.118, -25.126]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell006.geometry}
        material={nodes.Icosphere_cell008_cell001_cell006.material}
        position={[-39.757, 3.566, -20.1]}
      />
      <mesh
        geometry={nodes.Icosphere_cell008_cell001_cell007.geometry}
        material={nodes.Icosphere_cell008_cell001_cell007.material}
        position={[-36.717, 13.602, -22.484]}
      />
      <mesh
        geometry={nodes.Icosphere_cell016_cell001_cell001.geometry}
        material={nodes.Icosphere_cell016_cell001_cell001.material}
        position={[-16.89, -40.466, 5.904]}
      />
      <group position={[-18.671, -49.018, -3.279]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell001_1.geometry}
          material={nodes.Icosphere_cell016_cell001_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell001_2.geometry}
          material={nodes.Icosphere_cell016_cell001_cell001_2.material}
        />
      </group>
      <group position={[-7.913, -43.977, 8.887]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell002_1.geometry}
          material={nodes.Icosphere_cell016_cell001_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell002_2.geometry}
          material={nodes.Icosphere_cell016_cell001_cell002_2.material}
        />
      </group>
      <group position={[-16.332, -49.472, -1.877]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell003_1.geometry}
          material={nodes.Icosphere_cell016_cell001_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell003_2.geometry}
          material={nodes.Icosphere_cell016_cell001_cell003_2.material}
        />
      </group>
      <group position={[-16.713, -50.013, 0.204]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell004.geometry}
          material={nodes.Icosphere_cell016_cell001_cell004.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell001_cell004_1.geometry}
          material={nodes.Icosphere_cell016_cell001_cell004_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell016_cell001_cell007.geometry}
        material={nodes.Icosphere_cell016_cell001_cell007.material}
        position={[-8.701, -45.704, 13.378]}
      />
      <group position={[-16.642, -42.061, -4.741]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell008.geometry}
          material={nodes.Icosphere_cell016_cell_cell008.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell008_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell008_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell016_cell_cell001.geometry}
        material={nodes.Icosphere_cell016_cell_cell001.material}
        position={[-20.255, -39.674, 5.24]}
      />
      <group position={[-30.991, -40.881, 13.232]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell001_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell001_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell001_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell001_2.material}
        />
      </group>
      <group position={[-10.684, -44.736, 9.93]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell002_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell002_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell002_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell002_2.material}
        />
      </group>
      <group position={[-15.46, -46.059, 18.155]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell003_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell003_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell003_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell003_2.material}
        />
      </group>
      <group position={[-23.059, -43.995, 7.983]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell004_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell004_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell004_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell004_2.material}
        />
      </group>
      <group position={[-12.259, -53.634, 7.887]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell005_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell005_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell005_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell005_2.material}
        />
      </group>
      <group position={[-25.864, -36.601, 12.102]}>
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell006_1.geometry}
          material={nodes.Icosphere_cell016_cell_cell006_1.material}
        />
        <mesh
          geometry={nodes.Icosphere_cell016_cell_cell006_2.geometry}
          material={nodes.Icosphere_cell016_cell_cell006_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell.geometry}
        material={nodes.Icosphere_cell031_cell007_cell.material}
        position={[6.356, 18.266, -11.574]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell001.geometry}
        material={nodes.Icosphere_cell031_cell007_cell001.material}
        position={[-16.771, 29.598, -4.839]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell002.geometry}
        material={nodes.Icosphere_cell031_cell007_cell002.material}
        position={[-0.294, 7.282, 11.835]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell003.geometry}
        material={nodes.Icosphere_cell031_cell007_cell003.material}
        position={[14.396, 19.329, -7.793]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell004.geometry}
        material={nodes.Icosphere_cell031_cell007_cell004.material}
        position={[5.777, 31.956, -9.812]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell006.geometry}
        material={nodes.Icosphere_cell031_cell007_cell006.material}
        position={[4.301, 22.545, 16.091]}
      />
      <mesh
        geometry={nodes.Icosphere_cell031_cell007_cell007.geometry}
        material={nodes.Icosphere_cell031_cell007_cell007.material}
        position={[6.678, 21.044, 13.203]}
      />
    </group>
  );
}

useGLTF.preload("models/fuckoff.glb");
